[package]
name = "aegis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab_glyph = "0.2.21"
cgmath = "0.18.0"
glam = "0.24.0"
glium = "*"
